<?php


/**
 * Implementation of hook_services_resources_alter().
 */
function services_view_resource_services_resources_alter(&$resources, $endpoint) {
  $resources['node']['relationships']['view'] = array(
    'file' => array(
      'type' => 'inc', 
      'module' => 'services_view_resource',
      'name' => 'node',
    ),
    'help' => t('View node content.'),
    'access callback' => '_node_resource_access',
    'access arguments' => array('view'),
    'access callback file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/node_resource'),
    'access arguments append' => TRUE,
    'callback' => 'services_view_resource_node_view',
    'args' => array(
      array(
        'name' => 'nid',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'int',
        'description' => 'The nid of the node to view',
      ),
      array(
        'name' => 'build_mode',
        'type' => 'string',
        'description' => t('Build mode of node. Defaults to services_view_resource.'),
        'source' => array('param' => 'build_mode'),
        'optional' => TRUE,
      ),
    ),
  );
  $resources['comment']['relationships']['view'] = array(
    'file' => array(
      'type' => 'inc', 
      'module' => 'services_view_resource',
      'name' => 'comment',
    ),
    'help' => t('View comment content.'),
    'access callback' => '_comment_resource_access',
    'access arguments' => array('view'),
    'access callback file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/comment_resource'),
    'access arguments append' => TRUE,
    'callback' => 'services_view_resource_comment_view',
    'args' => array(
      array(
        'name' => 'cid',
        'optional' => FALSE,
        'source' => array('path' => 0),
        'type' => 'int',
        'description' => 'The cid of the comment to view',
      ),
    ),
  );
}

/**
 * Implementation of hook_content_build_modes().
 */
function services_view_resource_content_build_modes() {
  return array(
    'services_view_resource' => array(
      'title' => t('Services node view resource'), 
      'build modes' => array(
        'services_view_resource' => array(
          'title' => t('Services node view resource'), 
          'views style' => FALSE,
        ),
      ),
    ), 
  );
}